package logger

import (
	"context"

	"github.com/tokyobordel/traineepkg/context/trace"
)

// ExampleUsage демонстрирует использование ContextLogger
func ExampleUsage() {
	// Создаем новый ContextLogger
	logger, _ := NewContextLogger("", "", false)

	// Создаем контекст со spread
	ctx := context.Background()
	// Для всех внешния вызовов параметр spread остается пустым , тоесть со значением = ""
	// Кастомные названия spread нужен для системных вызовов, таких как запуск приложения.
	ctx = trace.WithSpread(ctx, "custom-spread-id")

	// Примеры различных методов логирования
	logger.Info(ctx, "Это информационное сообщение")
	logger.Infof(ctx, "Пользователь %s создан с ID %d", "john_doe", 123)

	logger.Debug(ctx, "Отладочная информация")
	logger.Debugf(ctx, "Значение переменной: %v", map[string]interface{}{"key": "value"})

	logger.Warn(ctx, "Предупреждение о потенциальной проблеме")
	logger.Warnf(ctx, "Неоптимальная операция выполнена за %d мс", 500)

	logger.Error(ctx, "Произошла ошибка")
	logger.Errorf(ctx, "Ошибка подключения к базе данных: %s", "connection timeout")

	// Использование с дополнительными полями
	entry := logger.WithField(ctx, "operation", "user_creation")
	entry.Info("Операция начата")

	entry = logger.WithFields(ctx, map[string]interface{}{
		"user_id":  123,
		"username": "john_doe",
		"action":   "login",
	})
	entry.Info("Пользователь вошел в систему")
}

// ExampleWithoutSpread показывает, что произойдет, если в контексте нет spread
func ExampleWithoutSpread() {
	logger, _ := NewContextLogger("", "", false)

	// Контекст без spread
	ctx := context.Background()

	// Логгер все равно будет работать, но spread будет "Spread not found"
	logger.Info(ctx, "Сообщение без spread в контексте")
}

// ExampleAutoGeneratedSpread показывает автоматическую генерацию spread
func ExampleAutoGeneratedSpread() {
	logger, _ := NewContextLogger("", "", false)

	// Создаем контекст с автоматически сгенерированным spread
	ctx := context.Background()
	ctx = trace.WithSpread(ctx, "") // пустая строка приведет к автогенерации

	logger.Info(ctx, "Сообщение с автоматически сгенерированным spread")
}
